"""Update My info

Revision ID: 14df7f993d90
Revises: 2aab794c2dd5
Create Date: 2026-02-07 16:36:32.443625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14df7f993d90'
down_revision: Union[str, None] = '2aab794c2dd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('myinfos', sa.Column('introduction', sa.Text(), nullable=False))
    op.alter_column('myinfos', 'bio',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('myinfos', 'bio',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('myinfos', 'introduction')
    # ### end Alembic commands ###
