"""update unique = true at CAchievement, Achievement Table

Revision ID: 4cda82d56ec2
Revises: ed48c3bb06be
Create Date: 2026-01-29 20:27:06.780673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cda82d56ec2'
down_revision: Union[str, None] = 'ed48c3bb06be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
