"""Update sever_default = func.now() for Project Table

Revision ID: 63f3dfe7f15a
Revises: 534370c2b07d
Create Date: 2026-01-26 11:05:27.723349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63f3dfe7f15a'
down_revision: Union[str, None] = '534370c2b07d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
