"""Cập nhật My info

Revision ID: 6ec3ced73a1a
Revises: 14df7f993d90
Create Date: 2026-02-10 13:56:03.896129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6ec3ced73a1a'
down_revision: Union[str, None] = '14df7f993d90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('myinfos', sa.Column('contact_links', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('myinfos', 'social_links')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('myinfos', sa.Column('social_links', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('myinfos', 'contact_links')
    # ### end Alembic commands ###
