"""Add cascade for blog category

Revision ID: b9e1237d30b7
Revises: 63f3dfe7f15a
Create Date: 2026-01-26 11:54:27.521203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9e1237d30b7'
down_revision: Union[str, None] = '63f3dfe7f15a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
