"""update table Blog, set default instead of sever_default, add default at last_updated column

Revision ID: c571c903d3b6
Revises: b9e1237d30b7
Create Date: 2026-01-28 19:58:36.070476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c571c903d3b6'
down_revision: Union[str, None] = 'b9e1237d30b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
